# Generated by Django 4.1.13 on 2024-11-09 17:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("someday", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="calendarevent",
            name="user",
        ),
    ]
