# Generated by Django 4.1.13 on 2024-11-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("someday", "0002_remove_calendarevent_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_trained", "Not Trained"),
                            ("training", "Training"),
                            ("trained", "Trained"),
                        ],
                        default="not_trained",
                        max_length=20,
                    ),
                ),
                ("last_trained", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "modelstatus",
            },
        ),
    ]
